src/pratododia-project/Controllers/ReceitasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using pratododia_project.Models;
using pratododia_project.ViewModels;
using System.Security.Claims;

namespace pratododia_project.Controllers

{
    [Authorize]
    public class ReceitasController : Controller
    {
        private readonly IWebHostEnvironment _webHost;
        private readonly AppDbContext _context;

        public ReceitasController(AppDbContext context, IWebHostEnvironment webHost)
        {
            _context = context;
            _webHost = webHost;
        }

        // Create GET
        public async Task<IActionResult> Create()
        {
            var ViewModel = new ReceitaIngredienteViewModel
            {
                Ingredientes = await _context.Ingredientes.ToListAsync(),
                IngredientesSelecionados = new List<IngredienteViewModel>()
            };

            return View(ViewModel);
        }

        // Create POST
        [HttpPost]
        public async Task<IActionResult> Create(ReceitaIngredienteViewModel model, IFormFile file)
        {
            if (!ModelState.IsValid)
            {
                model.Ingredientes = await _context.Ingredientes.ToListAsync();
                return View(model);
            }

            model.IngredientesSelecionados ??= new List<IngredienteViewModel>();

            var userIdString = User.FindFirstValue(ClaimTypes.NameIdentifier);
            int userId = int.Parse(userIdString);

            string imagensFolder = Path.Combine(_webHost.WebRootPath, "ImagensReceitas");

            if (!Directory.Exists(imagensFolder))
            {
                Directory.CreateDirectory(imagensFolder);
            }

            string fileName;

            if (file != null && file.Length > 0)
            {
                fileName = Path.GetFileName(file.FileName);
                string fileSavePath = Path.Combine(imagensFolder, fileName);

                using (FileStream stream = new FileStream(fileSavePath, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }

                model.CaminhoImg = Path.Combine("ImagensReceitas", fileName);
            }

            else
            {
                model.CaminhoImg = Path.Combine("img", "semImagem.png");
            }

            var receita = new Receita
            {
                IdUsuario = userId,
                DataPublicacao = DateTime.Now,
                CaminhoImg = model.CaminhoImg,
                NomeReceita = model.NomeReceita,
                Descricao = model.Descricao,
                TempoPreparo = model.TempoPreparo,
                Dificuldade = model.Dificuldade,
                Rendimento = model.Rendimento,
                Categoria = model.Categoria,
                Passos = model.Passos
            };

            _context.Add(receita);
            await _context.SaveChangesAsync(); // Salva a receita e gera o ID

            // Associe os ingredientes à receita
            foreach (var ingredienteVm in model.IngredientesSelecionados)
            {
                // Verifique se o IdIngrediente está preenchido
                if (ingredienteVm.IdIngrediente > 0 && ingredienteVm.Quantidade > 0)
                {
                    var ingredienteReceita = new IngredienteReceita
                    {
                        IdReceita = receita.IdReceita,
                        IdIngrediente = ingredienteVm.IdIngrediente,
                        Quantidade = ingredienteVm.Quantidade,
                        Tipo = ingredienteVm.Tipo
                    };

                    _context.Add(ingredienteReceita);
                }

                else
                {
                    model.Ingredientes = await _context.Ingredientes.ToListAsync();
                    return View(model);
                }
            }

            await _context.SaveChangesAsync(); // Salva a lista de ingredientes associada à receita
            return RedirectToAction("Details", new { id = receita.IdReceita });

        }

        // Details GET
        [AllowAnonymous]
        [HttpGet("Receitas/Details/{id:int}")]
        public async Task<IActionResult> Details(int id)
        {
            Receita receita = await _context.Receitas
           .Include(r => r.Usuario)
           .Include(r => r.Comentarios)
               .ThenInclude(c => c.Usuario)
            .Include(r => r.Comentarios)
               .ThenInclude(c => c.RespostasComentario)
               .ThenInclude(rc => rc.Usuario)
            .FirstOrDefaultAsync(r => r.IdReceita == id);

            var ingredientes = await _context.IngredientesReceitas
                                            .Where(i => i.IdReceita == id)
                                            .Include(i => i.Ingrediente)
                                            .ToListAsync();
            if (receita == null)
            {
                return NotFound();
            }
            // Acessos++
            receita.Acessos++;
            await _context.SaveChangesAsync();

            var userId = User.Identity.IsAuthenticated ? User.FindFirstValue(ClaimTypes.NameIdentifier) : null;
            int parsedUserId;
            var usuario = (userId != null) ? await _context.Usuarios.FirstOrDefaultAsync(user => user.IdUsuario == int.Parse(userId)) : null;
            var Passos = receita.Passos.ToList();
            var receitasmaisvistas = await _context.Receitas.OrderByDescending(r => r.Acessos).Take(10).ToListAsync();
            var receitasmaiscomentadas = await _context.Receitas.Select(r => new { Receita = r, nComments = _context.Comentarios.Count(c => c.IdReceita == r.IdReceita) }).OrderByDescending(r => r.nComments).Take(10).Select(r => r.Receita).ToListAsync();
            var receitasmaisavaliadas = await _context.Receitas.OrderByDescending(r => r.Avaliacao).Take(10).ToListAsync();

            var viewModel = new ReceitaVM
            {
                Usuario = usuario,
                Receita = receita,
                eSalva = false,
                Passo = Passos,
                Ingredientes = ingredientes,
                Comentarios = receita.Comentarios.ToList(),
                ReceitaMaisComentadas = receitasmaiscomentadas,
                ReceitaMaisVistas = receitasmaisvistas,
                ReceitaMaisAvaliadas = receitasmaisavaliadas
            };

            if (userId != null && int.TryParse(userId, out parsedUserId))
            {
                var tryRate = await _context.RatedRecipes.FirstOrDefaultAsync(ra => ra.IdReceita == id && ra.IdUsuario == parsedUserId);
                viewModel.MinhaNota = tryRate == null ? 0 : tryRate.Nota;
                viewModel.eSalva = _context.SavedRecipes.Any(s => s.IdReceita == receita.IdReceita && s.IdUsuario == int.Parse(userId));
            }
            else
            {
                viewModel.MinhaNota = 0;
            }
            return View(viewModel);
        }

        // Edit GET
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            // User
            var getUserId = User.Identity.IsAuthenticated ? User.FindFirstValue(ClaimTypes.NameIdentifier) : null;
            int userId = 0;
            if (getUserId != null && !int.TryParse(getUserId, out userId))
            {
                return Unauthorized();  // Caso o ID não seja um número válido
            }

            if (id == null)
            {
                return NotFound();
            }

            // Recipe
            var receita = await _context.Receitas
                .Include(r => r.IngredientesReceitas)
                .ThenInclude(ir => ir.Ingrediente)
                .FirstOrDefaultAsync(r => r.IdReceita == id);

            if (receita == null || userId != receita.IdUsuario)
            {
                var user = await _context.Usuarios.FirstOrDefaultAsync(u => u.IdUsuario == userId);
                if (user == null || !user.IsAdmin)
                {
                    return NotFound();
                }
            }
            // Selected Ing Id's
            var selectedIngredientIds = _context.IngredientesReceitas
                .Where(ir => ir.IdReceita == id)
                .Select(ir => ir.IdIngrediente)
                .ToList();

            // Selected Ingredients
            var ingredientesselecionados = _context.IngredientesReceitas
                .Where(ir => ir.IdReceita == id)
                .Select(ir => new IngredienteViewModel
                {
                    IdIngrediente = ir.IdIngrediente,
                    Quantidade = ir.Quantidade,
                    Tipo = ir.Tipo,
                    Nome = ir.Ingrediente.Nome
                })
                .ToList();

            // Avaliable Ingredients
            var ingredients = await _context.Ingredientes
                .Where(i => !selectedIngredientIds.Contains(i.IdIngrediente))
                .OrderBy(i => i.Nome)
                .ToListAsync();

            //ViewModel
            var ViewModel = new ReceitaIngredienteViewModel
            {
                CaminhoImg = receita.CaminhoImg,
                NomeReceita = receita.NomeReceita,
                Descricao = receita.Descricao,
                TempoPreparo = receita.TempoPreparo,
                Rendimento = receita.Rendimento,
                Categoria = receita.Categoria,
                Passos = receita.Passos,
                Ingredientes = ingredients,
                IngredientesSelecionados = ingredientesselecionados
            };

            return View(ViewModel);
        }

        // Edit POST
        [HttpPost]
        public async Task<IActionResult> Edit(int id, ReceitaIngredienteViewModel model, IFormFile file)
        {
            model.Ingredientes = await _context.Ingredientes.ToListAsync();

            var userIdString = User.FindFirstValue(ClaimTypes.NameIdentifier);

src/pratododia-project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Prato do Dia</title>
    <link rel="stylesheet" href="~/css/modules/render.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/modules/root.css" asp-append-version="true" />
    @if (!ViewData["NoBootstrap"]?.Equals(true) ?? true)
    {
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    }

    @RenderSection("Styles", required: false)
</head>
<body class="f-column">
    @if (ViewBag.ShowHeader != false)
    {
        <header>
            <div id="containerHeader">
                <a id="logoHeader" asp-action="Index" asp-controller="Home">
                    <img src="~/img/extendedLogoWhite.png" alt="Logo" id="imgLogo" />
                    <img src="~/img/shortLogo.png" alt="Logo" id="imgShortLogo">
                </a>
                <div id="searchBar">
                    <input type="text" id="searchInput" placeholder="Busque por receitas!" name="nomeReceita" value="@ViewBag.NomeReceita">
                    <button id="submitBtn" type="submit" style="background: none; border: none; cursor: pointer;">
                        <img src="~/img/icons/search.png" alt="Search" id="searchIcon">
                    </button>
                </div>
                <div id="pagesBtns">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <div class="dropdown">

                            <button class="icon-large d-flex flex-column align-items-center" data-bs-toggle="dropdown" type="button" id="btnPage" style="border:none; filter: invert()">
                               <img src="~/img/icons/menu-hamburguer.png"/>
                            </button>


                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item d-flex flex-row justify-content-between gap-3" asp-area="" asp-controller="Home" asp-action="Index">
                                        Página Inicial
                                        <div class="icon-regular">
                                            <img src="~/img/icons/casa.png" />
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item d-flex flex-row justify-content-between gap-3" asp-area="" asp-controller="Receitas" asp-action="MinhasReceitas">
                                        Minhas Receitas
                                        <div class="icon-regular">
                                            <img src="~/img/icons/addreceita.png" />
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item d-flex flex-row justify-content-between gap-3" asp-area="" asp-controller="Usuarios" asp-action="Profile">
                                        Meu Perfil
                                        <div class="icon-regular">
                                            <img src="~/img/icons/User.png" />
                                        </div>
                                    </a>
                                </li>
                                <li><hr class="dropdown-divider"></hr></li>
                                <li>
                                    <form>
                                        <a class="dropdown-item d-flex flex-row justify-content-between gap-3" id="exitBtn" asp-area="" asp-controller="Usuarios" asp-action="Logout" style="border:none;">
                                            Sair
                                            <div class="icon-regular">
                                                <img src="~/img/icons/exit.png" />
                                            </div>
                                        </a>
                                    </form>
                                </li>
                            </ul>
                        </div>
                    }
                    else
                    {
                        <div class="lineDiv">
                            <a id="btnPage" class="btn" asp-area="" asp-controller="Usuarios" asp-action="Login">Entrar</a>
                            <div id="lineBtn"></div>
                        </div>
                    }

                </div>
            </div>
        </header>
    }
    <div class="grow-1 f-column">
        @RenderBody()
    </div>
    <footer><p id="copyrightTerms">© 2024 PratoDoDia. Todos os direitos reservados.</p></footer>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>